/** Real Excel (.xlsx) and Word (.doc) exports from extracted fields */
window.DocOfficeExport = (function () {
  function getFieldsMap(fields) {
    return Object.fromEntries(fields.map((f) => [f.key, f.value]));
  }

  function downloadBlob(blob, filename) {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 4000);
  }

  function slug(name) {
    return (name || 'document').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'export';
  }

  function downloadExcelWorkbook(fields, rentRoll, meta) {
    if (!window.XLSX) throw new Error('SheetJS not loaded');
    const data = getFieldsMap(fields);
    const base = slug(data.property_name || meta.fileName);

    const summary = [
      ['CRE Document Intelligence — Workout Export'],
      ['Source file', meta.fileName || '—'],
      ['Pages parsed', meta.pages || '—'],
      ['Exported', new Date().toLocaleString()],
      [],
      ['Field', 'Value', 'Confidence'],
      ...fields.map((f) => [f.label, f.value, `${f.confidence}%`]),
    ];

    const model = [
      ['Underwriting model inputs'],
      ['Field', 'Value', 'Notes'],
      ['UPB', data.upb || '', 'Pulled from extraction'],
      ['DSCR', data.dscr || '', ''],
      ['LTV', data.ltv || '', ''],
      ['NOI', data.noi || '', ''],
      ['Occupancy', data.occupancy || '', ''],
      ['As-is value', data.collateral_value || '', ''],
      ['Days delinquent', data.delinquency || '', ''],
    ];

    const rentHeader = ['Unit', 'Type', 'SF', 'Tenant', 'Lease Start', 'Lease End', 'Monthly Rent', 'Status'];
    const rentRows = rentRoll.map((r) => [r.unit, r.type, r.sf, r.tenant, r.start, r.end, r.rent, r.status]);

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summary), 'Summary');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(model), 'Workout Model');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([rentHeader, ...rentRows]), 'Rent Roll');

    const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
    downloadBlob(new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), `${base}-workout.xlsx`);
  }

  function copyExcelPaste(fields) {
    const rows = [['Field', 'Value', 'Confidence'], ...fields.map((f) => [f.label, f.value, f.confidence])];
    const tsv = rows.map((r) => r.join('\t')).join('\n');
    return navigator.clipboard.writeText(tsv);
  }

  function downloadWordMemo(fields, meta) {
    const d = getFieldsMap(fields);
    const title = d.property_name || 'Workout Memo';
    const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${title}</title></head>
<body style="font-family: Calibri, sans-serif; font-size: 11pt;">
  <h1 style="font-size: 16pt;">NPL Workout Memo</h1>
  <p><strong>Source:</strong> ${meta.fileName || 'Uploaded document'} · ${meta.pages ? meta.pages + ' pages' : ''}</p>
  <h2 style="font-size: 13pt;">Loan &amp; collateral summary</h2>
  <table border="1" cellpadding="6" cellspacing="0" style="border-collapse: collapse; width: 100%;">
    <tr><td><strong>Loan ID</strong></td><td>${d.loan_id || '—'}</td></tr>
    <tr><td><strong>Collateral</strong></td><td>${d.property_name || '—'}</td></tr>
    <tr><td><strong>UPB</strong></td><td>${d.upb || '—'}</td></tr>
    <tr><td><strong>Days delinquent</strong></td><td>${d.delinquency || '—'}</td></tr>
    <tr><td><strong>DSCR</strong></td><td>${d.dscr || '—'}</td></tr>
    <tr><td><strong>LTV</strong></td><td>${d.ltv || '—'}</td></tr>
    <tr><td><strong>NOI</strong></td><td>${d.noi || '—'}</td></tr>
    <tr><td><strong>Occupancy</strong></td><td>${d.occupancy || '—'}</td></tr>
    <tr><td><strong>As-is value</strong></td><td>${d.collateral_value || '—'}</td></tr>
    <tr><td><strong>Workout status</strong></td><td>${d.workout_status || '—'}</td></tr>
  </table>
  <h2 style="font-size: 13pt;">Recommendation</h2>
  <p>${d.workout_status || 'Pending review after field validation.'}</p>
  <p style="color: #666; font-size: 9pt;">Generated by Sean Aguinaga doc-intelligence experiment · ${new Date().toLocaleDateString()}</p>
</body></html>`;
    downloadBlob(new Blob(['\ufeff', html], { type: 'application/msword' }), `${slug(title)}-memo.doc`);
  }

  return { downloadExcelWorkbook, copyExcelPaste, downloadWordMemo };
})();